### ISSUE TITLE
Problem: C4Social process needs a synopsis and introductory text

### ISSUE THREAD

**Issue by aschrijver** [c4social/c4social.org#8]
The README mentions:

> "To me it sounded perfect for FLOSS so I wondered why the process not more widely adopted. My best guess is that people just haven't tried it."

I think I can list some reasons. The [C4 Spec](https://rfc.zeromq.org/spec/42/) has a reasonable Abstract and an appealing set of Goals, but is otherwise a quite formal specification full of SHALL and MUST bullet points of which the implications aren't really clear unless one takes the time to study them thoroughly. In a similar vein the [C4 Process documentation](https://zguide.zeromq.org/docs/chapter6/#The-ZeroMQ-Process-C) at the ZeroMQ website is a wall of text, that takes similar amount of time and attention to parse.

What is needed IMHO is a good synopsis and introductory text for noobs that can be consumed really quickly. A cheat-sheet if you will, and maybe having some process diagrams as well. In other words, some kind of article with 4-5 mins of read-time, after which one says "I really NEED this".

**Comment by weex** [comment]
https://c4social.org/why-c4/ is now available so @aschrijver you may close this if you consider this problem solved.
